// <auto-generated />
using Legacy.Maliev.ContactService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure;

#nullable disable

namespace Legacy.Maliev.ContactService.Data.Migrations;

[DbContext(typeof(ContactRequestDbContext))]
[Migration("20260807143100_AlignUtcTimestampColumns")]
partial class AlignUtcTimestampColumns
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Legacy.Maliev.ContactService.Domain.ContactRequest", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("ID");
            b.Property<string>("Company").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("Country").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<DateTime?>("CreatedDate")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp without time zone")
                .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");
            b.Property<string>("Email").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("FirstName").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("LastName").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("MessageContent").HasColumnType("text");
            b.Property<DateTime?>("ModifiedDate")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp without time zone")
                .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");
            b.Property<string>("Telephone").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<uint>("Version").IsRowVersion().HasColumnType("xid");
            b.HasKey("Id");
            b.ToTable("Message");
        });
    }
}
